FROM python:3.10-slim-bullseye

RUN apt-get update \
&& apt-get install -y --no-install-recommends gcc libpq-dev \
&& apt-get clean \
&& rm -rf var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements.txt /app/

RUN pip install --no-cache-dir --upgrade pip \
&& pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 5000

CMD ["uvicorn", "server:server", "--host", "0.0.0.0", "--port", "5000"]
